"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

import sys
sys.setrecursionlimit(5000)

APP = ["openassistant.py"]
DATA_FILES = ['vacuum_cleaner_icon_250389.png',
              'mistral-7b-openorca.Q5_K_M.gguf']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'vacuum_cleaner_icon_250389.png',
    'plist': {
        'CFBundleName': 'OpenAssistant',
        'CFBundleDisplayName': 'OpenAssistant',
        'CFBundleVersion': "1.0.0"
    },
    'packages': ['certifi', 'llama_cpp', 'whisper', 'pyaudio', 'wave']   
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
